require_relative 'support'

RSpec.describe Equipment::Catalog do
  describe 'autogenerated Spell-Form Item Types' do
    let(:spells) do
      [
        { 'name' => 'Heal',  'tier' => [0, 1, 2], 'items' => %w[potion oil] },
        { 'name' => 'Ward',  'tier' => [0, 1],    'items' => %w[potion oil] },
        { 'name' => 'Grease','tier' => 1,         'items' => %w[oil] },
        { 'name' => 'Bolt',  'tier' => 0 } # no items: -> Scroll/Wand only
      ]
    end
    let(:catalog) { described_class.new({}, spells: spells) }

    it 'makes a Scroll and a Wand for every spell' do
      %w[Heal Ward Grease Bolt].each do |sp|
        scroll = catalog.item_type("Scroll of #{sp}")
        wand   = catalog.item_type("Wand of #{sp}")
        expect(scroll[:category]).to eq('Consumable')
        expect(scroll[:definition]['spell']).to eq(sp)
        expect(wand[:category]).to eq('Item')
        expect(wand[:definition]['slot']).to eq('hands')
        expect(wand[:definition]['grants_spell']).to be true
      end
    end

    it 'gates Potion / Oil on the spell\'s items: list' do
      expect(catalog.item_type('Potion of Heal')).not_to be_nil
      expect(catalog.item_type('Oil of Heal')).not_to be_nil
      expect(catalog.item_type('Potion of Ward')).not_to be_nil
      # Grease is oil-only; Bolt has no item forms beyond Scroll/Wand.
      expect(catalog.item_type('Oil of Grease')).not_to be_nil
      expect(catalog.item_type('Potion of Grease')).to be_nil
      expect(catalog.item_type('Potion of Bolt')).to be_nil
      expect(catalog.item_type('Oil of Bolt')).to be_nil
    end

    it 'carries the spell tier and marks consumable forms innately usable' do
      potion = catalog.item_type('Potion of Heal')[:definition]
      expect(potion['tier']).to eq([0, 1, 2])
      expect(potion['innately_usable']).to be true
    end

    it 'lists generated Consumables in item_types_in_category' do
      consumables = catalog.item_types_in_category('Consumable')
      expect(consumables).to include('Scroll of Heal', 'Potion of Heal', 'Oil of Grease')
    end

    it 'lets a handwritten entry override a generated form of the same name' do
      authored = described_class.new(
        { 'Consumables' => { 'Scroll of Heal' => { 'spell' => 'Heal', 'base_price' => 999 } } },
        spells: spells
      )
      expect(authored.definition_of('Scroll of Heal')['base_price']).to eq(999)
    end

    it 'generates nothing when no spells are injected (handcrafted catalogs)' do
      expect(described_class.new({}).item_type('Scroll of Heal')).to be_nil
    end
  end

  describe 'autogenerated Poison Vials' do
    let(:catalog) { described_class.new({}, poisons: %w[spider_venom sleep_venom]) }

    it 'makes one Consumable "Vial of <Poison>" per poison, title-cased' do
      vial = catalog.item_type('Vial of Spider Venom')
      expect(vial[:category]).to eq('Consumable')
      expect(vial[:definition]['poison']).to eq('spider_venom')
      expect(catalog.item_type('Vial of Sleep Venom')).not_to be_nil
    end

    it 'lists generated vials in the Consumable category' do
      expect(catalog.item_types_in_category('Consumable'))
        .to include('Vial of Spider Venom', 'Vial of Sleep Venom')
    end

    it 'generates no vials when no poisons are injected' do
      expect(described_class.new({}).item_type('Vial of Spider Venom')).to be_nil
    end
  end

  describe 'the shipped catalog' do
    let(:catalog) { described_class.load }

    it 'adds the Bola as a thrown, zero-damage-field weapon with a prone save' do
      bola = catalog.item_type('Bola')
      expect(bola[:category]).to eq('Weapon')
      d = bola[:definition]
      expect(d['base_damage']).to eq(0)
      expect(d['tags']).to include('thrown')
      expect(d['tags']).not_to include('lesslethal')
      expect(d['range_feet']).to eq(10)
      expect(d['on_hit_save']).to include('attribute' => 'str', 'fail' => 'prone')
    end

    it 'autogenerates Poison Vials from the real Conditions poison catalog' do
      vial = catalog.item_type('Vial of Spider Venom')
      expect(vial[:category]).to eq('Consumable')
      expect(vial[:definition]['poison']).to eq('spider_venom')
    end

    it 'adds Kerosene as a slotless generic Item' do
      kerosene = catalog.item_type('Kerosene')
      expect(kerosene[:category]).to eq('Item')
      expect(kerosene[:definition]['slot']).to be_nil
    end

    it 'pins the Tattoo of the Viper grant to Class Level 1 and prices it at 5000' do
      tattoo = catalog.item_type('Tattoo of the Viper')
      expect(tattoo[:category]).to eq('Tattoo')
      expect(tattoo[:definition]['grants']).to eq([{ 'ability' => 'Sneak Attack', 'class_level' => 1 }])
      expect(catalog.base_price_for('Tattoo of the Viper', 0)).to eq(5000)
    end

    it "adds Kesser's Ring as a no-store unique Item granting Kesser's Gambit" do
      ring = catalog.item_type("Kesser's Ring")
      expect(ring[:category]).to eq('Item')
      # slot + category are inherited from the generic Ring base (inherits_from).
      expect(ring[:definition]['slot']).to eq('finger')
      expect(ring[:definition]['no_store']).to be true
      expect(ring[:definition]['grants']).to include("Kesser's Gambit")
      # A Unique Item never borrows the base's gold value.
      expect(ring[:definition]).not_to have_key('base_price')
    end

    it 'inherits_from fills in a base Type traits (slot/category) but not its price' do
      expect(catalog.item_type('Ring')[:definition]['base_price']).to eq(5)

      parry = catalog.item_type('Ring of Parry')
      expect(parry[:category]).to eq('Item')           # borrowed from Ring
      expect(parry[:definition]['slot']).to eq('finger') # borrowed from Ring
      expect(parry[:definition]['inherits_from']).to eq('Ring')
      expect(parry[:definition]['grants_parry']).to be true   # its own
      expect(parry[:definition]['no_store']).to be true       # its own
      expect(parry[:definition]).not_to have_key('base_price') # never the base's
    end

    it 'autogenerates Potion forms only for eligible spells (incl. the new ones)' do
      expect(catalog.item_type('Potion of Heal')).not_to be_nil
      expect(catalog.item_type('Potion of Recharge')).not_to be_nil
      expect(catalog.item_type('Potion of Expeditious Retreat')).not_to be_nil
      expect(catalog.item_type('Potion of Grease')).to be_nil
    end
  end
end
