# Check Resolution Configuration

Die Size: 10
Minimum Dice: 6
Dice Range: 5
Attribute Contribution Formula: "<Attribute> / 2"
Dice Cap Formula: "<Minimum Dice> + ((<Attribute Contribution Formula> + <Prowess>) % <Dice Range>)"
Base Target Number: 8
Minimum Target Number: 3
Maximum Target Number: 9
Default Success Threshold: 2
Default Fumble Threshold: 2

# Single-character labels for die values 10+ in an Dice Result String.
# Values 1-9 use '1'-'9'. Values 10+ use characters from this string.
# If this string is too short to cover every possible values then 
# instead use A,B,C … Z. Boot errors if encoding is non-monotonic
Dice Result String Encoding: "X"
