# Damage Configuration

Death Multiplier: 2.0
Ascendancy Damage Reduction Per Tier: 5

Death Threshold Formula: "floor(<Death Multiplier> * <Track Maximum>)"
Ascendancy Damage Reduction Formula: "floor(<Ascendancy Damage Reduction Per Tier> * <Tier Gap>)"
Acid Damage Formula: "floor(<Acid Counter> / 2)"
